name: Alerta CRM

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  alerta:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        run: python alerta_crm.py
